### ISSUE TITLE
subClassOf IntersectionOfs

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon-phenoscape-ext#19]
two axioms are untranslatable to .obo blocking #18  

# Class: <http://purl.obolibrary.org/obo/UBERON_3000112> (crista dentalis of premaxilla)

SubClassOf(<http://purl.obolibrary.org/obo/UBERON_3000112>
           ObjectSomeValuesFrom(
                <http://purl.obolibrary.org/obo/BFO_0000050>
                ObjectIntersectionOf(<http://purl.obolibrary.org/obo/UBERON_0004103>
                         ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0002244>))))

# Class: <http://purl.obolibrary.org/obo/UBERON_4500020> (pelvic fin distal radial cartilage)

SubClassOf(<http://purl.obolibrary.org/obo/UBERON_4500020>
           ObjectIntersectionOf(
                    <http://purl.obolibrary.org/obo/UBERON_1600008>
                    ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002473> <http://purl.obolibrary.org/obo/UBERON_0002418>)))

Both of these can easily be rewritten to simple relation graph form

 * C subClassOf part-of some (D and part-of some E) ==>
      * C subClassOf part-of some D
      * C subClassOf part-of some E
  * C subClassOf D and part-of some E ==>
      * C subClassOf D
      * C subClassOf part-of some E

**Comment by cmungall** [comment]
oops - obvious mistake in my first transformation - that makes it a weaker axiom...

**Comment by cmungall** [comment]
but thankfully we have a named class

alveolar ridge of premaxilla =
'alveolar ridge'
 and ('part of' some premaxilla)

**Comment by wdahdul** [comment]
Thanks Chris, these changes were merged into phenoscape-ext today.
