### ISSUE TITLE
plectral apparatus def and synonyms

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon-phenoscape-ext#4]
_From @wdahdul on September 30, 2016 19:9_

Updates to the existing term plectral apparatus UBERON_3000443:

exact synonym: plectrum
related synonyms: stapes, columella, columella auris (citation: http://www.nature.com/articles/srep34130)

Def: Combined element that is the ossified footplate and ossified stylus that are, together, called the columella or stapes, as well as the distal cartilaginous parts bound to the tympanic ring. [PHENOSCAPE:DB]

Notes: Most authors would refer to this as the columella or stapes, but the plectrum also consists of a third component (distal parts), thus correspondence of frog columella and mammalian stapes is not certain.

_Copied from original issue: obophenotype/uberon#1274_

**Comment by cmungall** [comment]
may also want to coordinate with @ANiknejad on homology assertion

**Comment by fbastian** [comment]
@Aniknejad: anything impacting our homology annotations?

**Comment by ANiknejad** [comment]
@fbastian 
so far no annotation on UBERON:3000443, paper not yet annotated, will do it.

Anyway, I already reported a new conflicting evidence about mammals middle ear from this paper:

https://www.ncbi.nlm.nih.gov/pubmed/?term=27563341

current historical homology annotation for UBERON:0001756 middle ear are:

middle ear		8292	Amphibia
middle ear		8457	Sauropsida
middle ear		8459	Testudines
middle ear		8492	Archosauria
middle ear		8504	Lepidosauria
middle ear	NOT	     32524	     Amniota
middle ear		40674	Mammalia
middle ear	NOT	     40674	     Mammalia
middle ear		32525	Theria
middle ear		9255	Monotremata

Please let me know if something is weird here

**Comment by balhoff** [comment]
This repo is closing; open a ticket for this at the main Uberon repo if it's still needed.
